name: mkdocs-build
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: poetry
      - run: poetry install --only mkdocs
      - run: poetry run mkdocs build
